// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineConsultations.Data;

#nullable disable

namespace OnlineConsultations.Data.Migrations
{
    [DbContext(typeof(OnlineConsultationsDbContext))]
    [Migration("20241107200734_Seed-migration")]
    partial class Seedmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<DateTime>("AnswerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnswerDescription")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvideUserId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("ProvideUserId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer First",
                            ProvideUserId = 1,
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 2,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer Second",
                            ProvideUserId = 1,
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 3,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer Third",
                            ProvideUserId = 1,
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 4,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer Fourth",
                            ProvideUserId = 2,
                            QuestionId = 1
                        },
                        new
                        {
                            AnswerId = 5,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer Fifth",
                            ProvideUserId = 2,
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 6,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer Sixth",
                            ProvideUserId = 2,
                            QuestionId = 3
                        },
                        new
                        {
                            AnswerId = 7,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer Seventh",
                            ProvideUserId = 3,
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 8,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer Eighth",
                            ProvideUserId = 3,
                            QuestionId = 2
                        },
                        new
                        {
                            AnswerId = 9,
                            AnswerDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnswerDescription = "Answer Ninth",
                            ProvideUserId = 3,
                            QuestionId = 3
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin@admin.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0f2cb6ec-5d22-4b92-8e46-4736f1a6cff1",
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            FirstName = "AdminFirstName",
                            LastName = "AdminLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEFxlY6h9qfYueFS4o+LbuttO/HKnXRttsEQahzaYEbzEzA5Zw1lLnMVTVVL0WCt5cQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eccb1f6f-e5dc-406a-b915-f8ba60516d77",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "guest1@guest.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4fbd193-549b-4034-abcd-57c6c81425be",
                            Email = "guest1@guest.com",
                            EmailConfirmed = false,
                            FirstName = "GuestOneFirstName",
                            LastName = "GuestOneLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMQaue3+H1CF4nWCcgwNTeI99aUePQZb+V3HheNqcEgAQoFsN0GIzOOG0yb8FXVSiw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "da873625-bf95-4484-aadb-c49c2ba03066",
                            TwoFactorEnabled = false,
                            UserName = "guest1@guest.com"
                        },
                        new
                        {
                            Id = "guest2@guest.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf88f0a8-3008-47ba-a9bf-def83807bd61",
                            Email = "guest2@guest.com",
                            EmailConfirmed = false,
                            FirstName = "GuestTwoFirstName",
                            LastName = "GuestTwoLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGDZuZ4vZI/w+mby8wBSG1UsWMQTUVR/2Vy1UtLAku3jsK7mv7S423K4vno8UZOJBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76c52747-ab56-4b9e-824a-3acb2edbf149",
                            TwoFactorEnabled = false,
                            UserName = "guest2@guest.com"
                        },
                        new
                        {
                            Id = "guest3@guest.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fdb9ed03-effe-4d24-880e-a13d8cc38723",
                            Email = "guest3@guest.com",
                            EmailConfirmed = false,
                            FirstName = "GuestThreeFirstName",
                            LastName = "GuestThreeLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEIpFfvs6YMpXKJ8hLoernXSjIcktK4mF2OElMHD69OqStoAY+a98rMk5J/2T8VeshQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e8607d4-b67a-4238-aca5-0edc50c34c9d",
                            TwoFactorEnabled = false,
                            UserName = "guest3@guest.com"
                        },
                        new
                        {
                            Id = "search1@search.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2edbff31-d963-423c-a02d-944bf7109763",
                            Email = "search1@search.com",
                            EmailConfirmed = false,
                            FirstName = "SearchOneFirstName",
                            LastName = "SearchOneLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGRPGXTmDEIl34EqxFdsu1QvbRfxPClB+BzNs2joh2G49Jb1TvqUu9lNZjOvlgZ7EA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3d89729-08c4-4a16-adf4-c9da4ec12bf9",
                            TwoFactorEnabled = false,
                            UserName = "search1@search.com"
                        },
                        new
                        {
                            Id = "search2@search.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2dbeaa6-cbc6-44a6-aeaa-949c5a4a4f70",
                            Email = "search2@search.com",
                            EmailConfirmed = false,
                            FirstName = "SearchTwoFirstName",
                            LastName = "SearchTwoLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJwekQUHgTY1cRu9mk9VCNUfnsLcBOo4gn3ZKdWmhXvIOArsXzWpbFUMGQVyzJ7AAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1c51a1e-9220-42c2-83e4-4f4f093ad416",
                            TwoFactorEnabled = false,
                            UserName = "search2@search.com"
                        },
                        new
                        {
                            Id = "search3@search.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74499b7a-a0d7-4eee-a81b-023d5c39dcd8",
                            Email = "search3@search.com",
                            EmailConfirmed = false,
                            FirstName = "SearchThreeFirstName",
                            LastName = "SearchThreeLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDhAh8HvenR2he+93FdxM/iH6lhDBCSe/JCrZ2jEXAEpXsYjd3+2A7gb9HNjFabMtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43bee3ec-7704-4d54-84a8-433b2d6c537b",
                            TwoFactorEnabled = false,
                            UserName = "search3@search.com"
                        },
                        new
                        {
                            Id = "provide1@provide.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9cc6af45-4932-4d26-97d9-2275d3cb87e1",
                            Email = "provide1@provide.com",
                            EmailConfirmed = false,
                            FirstName = "ProvideOneFirstName",
                            LastName = "ProvideOneLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEAkakCOY1y/Zv8g+K5z60oIIOf0UQs9g2doeEZwD2HmCiZK8Z+uWSJE7hs/+57p/zQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13eabb45-6f93-4dad-9ad4-e18279e7e115",
                            TwoFactorEnabled = false,
                            UserName = "provide1@provide.com"
                        },
                        new
                        {
                            Id = "provide2@provide.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae23081c-3476-48b0-906c-b0a98e7f7549",
                            Email = "provide2@provide.com",
                            EmailConfirmed = false,
                            FirstName = "ProvideTwoFirstName",
                            LastName = "ProvideTwoLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEO3Lvoy/pOq2RAOwkVcoUCOEgieCwC51aJrpi7kFUhZdH/ddV2XcFgyICmVvRzrw+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45d23a1c-c874-4fca-a55c-476998ae7436",
                            TwoFactorEnabled = false,
                            UserName = "provide2@provide.com"
                        },
                        new
                        {
                            Id = "provide3@provide.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6cf92602-861e-4e2e-a1ea-b2cae916d973",
                            Email = "provide3@provide.com",
                            EmailConfirmed = false,
                            FirstName = "ProvideThreeFirstName",
                            LastName = "ProvideThreeLastName",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJbN1m+aEpadhZfiF1AftdybFUtMg8k+4rcOE4M5nGzJ4nNVDUr+YNro231qFYyDoA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "34be6814-dac2-4974-a82d-9249300baf3b",
                            TwoFactorEnabled = false,
                            UserName = "provide3@provide.com"
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("CommentDescription")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GuestUserId")
                        .HasColumnType("int");

                    b.Property<int>("SearchUserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("SearchUserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            AnswerId = 1,
                            CommentDescription = "Comment First",
                            CommentTitle = "First",
                            GuestUserId = 1,
                            SearchUserId = 0
                        },
                        new
                        {
                            CommentId = 2,
                            AnswerId = 1,
                            CommentDescription = "Comment Second",
                            CommentTitle = "Second",
                            GuestUserId = 1,
                            SearchUserId = 0
                        },
                        new
                        {
                            CommentId = 3,
                            AnswerId = 2,
                            CommentDescription = "Comment Third",
                            CommentTitle = "Third",
                            GuestUserId = 2,
                            SearchUserId = 0
                        },
                        new
                        {
                            CommentId = 4,
                            AnswerId = 3,
                            CommentDescription = "Comment Fourth",
                            CommentTitle = "Fourth",
                            GuestUserId = 2,
                            SearchUserId = 0
                        },
                        new
                        {
                            CommentId = 5,
                            AnswerId = 3,
                            CommentDescription = "Comment Fifth",
                            CommentTitle = "Fifth",
                            GuestUserId = 1,
                            SearchUserId = 0
                        },
                        new
                        {
                            CommentId = 6,
                            AnswerId = 3,
                            CommentDescription = "Comment Sixth",
                            CommentTitle = "Sixth",
                            GuestUserId = 0,
                            SearchUserId = 1
                        },
                        new
                        {
                            CommentId = 7,
                            AnswerId = 2,
                            CommentDescription = "Comment Seventh",
                            CommentTitle = "Seventh",
                            GuestUserId = 0,
                            SearchUserId = 1
                        },
                        new
                        {
                            CommentId = 8,
                            AnswerId = 4,
                            CommentDescription = "Comment Eight",
                            CommentTitle = "Eight",
                            GuestUserId = 0,
                            SearchUserId = 2
                        },
                        new
                        {
                            CommentId = 9,
                            AnswerId = 1,
                            CommentDescription = "Comment Ninth",
                            CommentTitle = "Ninth",
                            GuestUserId = 0,
                            SearchUserId = 2
                        },
                        new
                        {
                            CommentId = 10,
                            AnswerId = 2,
                            CommentDescription = "Comment Tenth",
                            CommentTitle = "Tenth",
                            GuestUserId = 0,
                            SearchUserId = 2
                        },
                        new
                        {
                            CommentId = 11,
                            AnswerId = 2,
                            CommentDescription = "Comment Eleven",
                            CommentTitle = "Eleven",
                            GuestUserId = 0,
                            SearchUserId = 3
                        },
                        new
                        {
                            CommentId = 12,
                            AnswerId = 2,
                            CommentDescription = "Comment Twelve",
                            CommentTitle = "Twelve",
                            GuestUserId = 0,
                            SearchUserId = 3
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.GuestUser", b =>
                {
                    b.Property<int>("GuestUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestUserId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GuestUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("GuestUsers");

                    b.HasData(
                        new
                        {
                            GuestUserId = 1,
                            ApplicationUserId = "guest1@guest.com"
                        },
                        new
                        {
                            GuestUserId = 2,
                            ApplicationUserId = "guest2@guest.com"
                        },
                        new
                        {
                            GuestUserId = 3,
                            ApplicationUserId = "guest3@guest.com"
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("MessageDescription")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvideUserId")
                        .HasColumnType("int");

                    b.Property<int>("SearchUserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ProvideUserId");

                    b.HasIndex("SearchUserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            MessageDescription = "First message",
                            ProvideUserId = 1,
                            SearchUserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            MessageDescription = "Second message",
                            ProvideUserId = 1,
                            SearchUserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            MessageDescription = "Third message",
                            ProvideUserId = 2,
                            SearchUserId = 3
                        },
                        new
                        {
                            MessageId = 4,
                            MessageDescription = "Fourth message",
                            ProvideUserId = 1,
                            SearchUserId = 1
                        },
                        new
                        {
                            MessageId = 5,
                            MessageDescription = "Fifth message",
                            ProvideUserId = 3,
                            SearchUserId = 2
                        },
                        new
                        {
                            MessageId = 6,
                            MessageDescription = "Sixth message",
                            ProvideUserId = 1,
                            SearchUserId = 3
                        },
                        new
                        {
                            MessageId = 7,
                            MessageDescription = "Seventh message",
                            ProvideUserId = 3,
                            SearchUserId = 1
                        },
                        new
                        {
                            MessageId = 8,
                            MessageDescription = "Eight message",
                            ProvideUserId = 1,
                            SearchUserId = 2
                        },
                        new
                        {
                            MessageId = 9,
                            MessageDescription = "Ninth message",
                            ProvideUserId = 2,
                            SearchUserId = 1
                        },
                        new
                        {
                            MessageId = 10,
                            MessageDescription = "Tenth message",
                            ProvideUserId = 2,
                            SearchUserId = 3
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("PostDescription")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PostPayPerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProvideUserId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("ProvideUserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            PostDescription = "First Description",
                            PostPayPerHour = 22m,
                            PostTitle = "First post",
                            ProvideUserId = 1
                        },
                        new
                        {
                            PostId = 2,
                            PostDescription = "Second Description",
                            PostPayPerHour = 24m,
                            PostTitle = "Second post",
                            ProvideUserId = 2
                        },
                        new
                        {
                            PostId = 3,
                            PostDescription = "Third Description",
                            PostPayPerHour = 22m,
                            PostTitle = "Third post",
                            ProvideUserId = 3
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.ProvideUser", b =>
                {
                    b.Property<int>("ProvideUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvideUserId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProvideUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ProvideUsers");

                    b.HasData(
                        new
                        {
                            ProvideUserId = 1,
                            ApplicationUserId = "provide1@provide.com"
                        },
                        new
                        {
                            ProvideUserId = 2,
                            ApplicationUserId = "provide2@provide.com"
                        },
                        new
                        {
                            ProvideUserId = 3,
                            ApplicationUserId = "provide3@provide.com"
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("GuestUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("QuestionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionDescription")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SearchUserId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("GuestUserId");

                    b.HasIndex("SearchUserId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            GuestUserId = 0,
                            QuestionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionDescription = "First Description",
                            QuestionTitle = "First",
                            SearchUserId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            GuestUserId = 0,
                            QuestionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionDescription = "Second Description",
                            QuestionTitle = "Second",
                            SearchUserId = 2
                        },
                        new
                        {
                            QuestionId = 3,
                            GuestUserId = 0,
                            QuestionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionDescription = "Third Description",
                            QuestionTitle = "Third",
                            SearchUserId = 3
                        },
                        new
                        {
                            QuestionId = 4,
                            GuestUserId = 1,
                            QuestionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionDescription = "Fourth Description",
                            QuestionTitle = "Fourth",
                            SearchUserId = 0
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("ProvideUserId")
                        .HasColumnType("int");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.Property<int>("SearchUserId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("ProvideUserId");

                    b.HasIndex("SearchUserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            ProvideUserId = 1,
                            RatingValue = 10,
                            SearchUserId = 1
                        },
                        new
                        {
                            RatingId = 2,
                            ProvideUserId = 2,
                            RatingValue = 9,
                            SearchUserId = 1
                        },
                        new
                        {
                            RatingId = 3,
                            ProvideUserId = 3,
                            RatingValue = 8,
                            SearchUserId = 1
                        },
                        new
                        {
                            RatingId = 4,
                            ProvideUserId = 1,
                            RatingValue = 10,
                            SearchUserId = 2
                        },
                        new
                        {
                            RatingId = 5,
                            ProvideUserId = 2,
                            RatingValue = 9,
                            SearchUserId = 2
                        },
                        new
                        {
                            RatingId = 6,
                            ProvideUserId = 3,
                            RatingValue = 9,
                            SearchUserId = 2
                        },
                        new
                        {
                            RatingId = 7,
                            ProvideUserId = 1,
                            RatingValue = 8,
                            SearchUserId = 3
                        },
                        new
                        {
                            RatingId = 8,
                            ProvideUserId = 2,
                            RatingValue = 9,
                            SearchUserId = 3
                        },
                        new
                        {
                            RatingId = 9,
                            ProvideUserId = 3,
                            RatingValue = 10,
                            SearchUserId = 3
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("ProvideUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewDescription")
                        .IsRequired()
                        .HasMaxLength(200000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SearchUserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProvideUserId");

                    b.HasIndex("SearchUserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            ProvideUserId = 1,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "First description",
                            SearchUserId = 1
                        },
                        new
                        {
                            ReviewId = 2,
                            ProvideUserId = 2,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "Second description",
                            SearchUserId = 1
                        },
                        new
                        {
                            ReviewId = 3,
                            ProvideUserId = 3,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "Third description",
                            SearchUserId = 1
                        },
                        new
                        {
                            ReviewId = 4,
                            ProvideUserId = 1,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "Fourth description",
                            SearchUserId = 2
                        },
                        new
                        {
                            ReviewId = 5,
                            ProvideUserId = 2,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "Fifth description",
                            SearchUserId = 2
                        },
                        new
                        {
                            ReviewId = 6,
                            ProvideUserId = 3,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "Sixth description",
                            SearchUserId = 2
                        },
                        new
                        {
                            ReviewId = 7,
                            ProvideUserId = 1,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "Seventh description",
                            SearchUserId = 3
                        },
                        new
                        {
                            ReviewId = 8,
                            ProvideUserId = 2,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "Eight description",
                            SearchUserId = 3
                        },
                        new
                        {
                            ReviewId = 9,
                            ProvideUserId = 3,
                            ReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReviewDescription = "Ninth description",
                            SearchUserId = 3
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.SearchUser", b =>
                {
                    b.Property<int>("SearchUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchUserId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SearchUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("SearchUsers");

                    b.HasData(
                        new
                        {
                            SearchUserId = 1,
                            ApplicationUserId = "search1@search.com"
                        },
                        new
                        {
                            SearchUserId = 2,
                            ApplicationUserId = "search2@search.com"
                        },
                        new
                        {
                            SearchUserId = 3,
                            ApplicationUserId = "search3@search.com"
                        });
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineConsultations.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Answer", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ProvideUser", "ProvideUser")
                        .WithMany()
                        .HasForeignKey("ProvideUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineConsultations.Data.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvideUser");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Comment", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineConsultations.Data.Entities.GuestUser", "GuestUser")
                        .WithMany()
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineConsultations.Data.Entities.SearchUser", "SearchUser")
                        .WithMany()
                        .HasForeignKey("SearchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("GuestUser");

                    b.Navigation("SearchUser");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.GuestUser", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Message", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ProvideUser", "ProvideUser")
                        .WithMany()
                        .HasForeignKey("ProvideUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineConsultations.Data.Entities.SearchUser", "SearchUser")
                        .WithMany()
                        .HasForeignKey("SearchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvideUser");

                    b.Navigation("SearchUser");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Post", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ProvideUser", "ProvideUser")
                        .WithMany()
                        .HasForeignKey("ProvideUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvideUser");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.ProvideUser", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Question", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.GuestUser", "GuestUser")
                        .WithMany()
                        .HasForeignKey("GuestUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineConsultations.Data.Entities.SearchUser", "SearchUser")
                        .WithMany()
                        .HasForeignKey("SearchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestUser");

                    b.Navigation("SearchUser");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Rating", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ProvideUser", "ProvideUser")
                        .WithMany()
                        .HasForeignKey("ProvideUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineConsultations.Data.Entities.SearchUser", "SearchUser")
                        .WithMany()
                        .HasForeignKey("SearchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvideUser");

                    b.Navigation("SearchUser");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.Review", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ProvideUser", "ProvideUser")
                        .WithMany()
                        .HasForeignKey("ProvideUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineConsultations.Data.Entities.SearchUser", "SearchUser")
                        .WithMany()
                        .HasForeignKey("SearchUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProvideUser");

                    b.Navigation("SearchUser");
                });

            modelBuilder.Entity("OnlineConsultations.Data.Entities.SearchUser", b =>
                {
                    b.HasOne("OnlineConsultations.Data.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });
#pragma warning restore 612, 618
        }
    }
}
